services:
    loconox_entity_routing.slug.service.manager:
        class: Loconox\EntityRoutingBundle\Slug\SlugServiceManager
        tags:
            - { name: loconox_entity_routing.slug.service.manager }
