services:
    loconox_entity_routing.twig.extension.slug:
        class: Loconox\EntityRoutingBundle\Twig\SlugExtension
        arguments: [ '@Loconox\EntityRoutingBundle\Slug\SlugServiceManager' ]
        tags:
            - { name: twig.extension }
