services:
  loconox_entity_routing.validator.unique_slug:
    class: Loconox\EntityRoutingBundle\Validator\Constraints\UniqueSlugValidator
    arguments: [ '@Loconox\EntityRoutingBundle\Slug\SlugServiceManager', "@loconox_entity_routing.manager.slug" ]
    tags:
      - { name: validator.constraint_validator, alias: loconox_entity_routing.validator.unique_slug }
