language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

env:
  global:
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: SYMFONY=2.3.*
    - php: '7.1'
      env: SYMFONY=2.7.*
    - php: '7.1'
      env: SYMFONY=2.8.*
    - php: '7.1'
      env: SYMFONY=3.2.*
    - php: '7.1'
      env: SYMFONY=3.3.*
    - php: '7.1'
      env: SYMFONY=dev-master@dev
  allow_failures:
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: phpunit --coverage-text