services:
  loconox_entity_routing.router:
    class: Loconox\EntityRoutingBundle\Route\SlugRouter
    arguments: [ '@Loconox\EntityRoutingBundle\Slug\SlugServiceManager', "@loconox_entity_routing.manager.slug", "%loconox_entity_routing.router.resource%", "%loconox_entity_routing.router.resource_type%", "@loconox_entity_routing.route.loader" ]

  loconox_entity_routing.route.loader_resolver:
    class: Symfony\Component\Config\Loader\LoaderResolver

  loconox_entity_routing.route.loader:
    class: Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader
    arguments: [ "@loconox_entity_routing.route.loader_resolver" ]

  loconox_entity_routing.route.loader.annotation:
    class: Symfony\Bundle\FrameworkBundle\Routing\AnnotatedRouteControllerLoader
    arguments: [ "@annotation_reader" ]
    calls:
      - [ setRouteAnnotationClass, [ Loconox\EntityRoutingBundle\Annotation\Route ] ]
    tags:
      - { name: loconox_entity_routing.loader, priority: -10 }

  loconox_entity_routing.route.loader.annotation.dir:
    class: Symfony\Component\Routing\Loader\AnnotationDirectoryLoader
    arguments: [ "@file_locator", "@loconox_entity_routing.route.loader.annotation" ]
    tags:
      - { name: loconox_entity_routing.loader, priority: -10 }

  loconox_entity_routing.route.loader.annotation.file:
    class: Symfony\Component\Routing\Loader\AnnotationFileLoader
    arguments: [ "@file_locator", "@loconox_entity_routing.route.loader.annotation" ]
    tags:
      - { name: loconox_entity_routing.loader, priority: -10 }

  loconox_entity_routing.route.loader.psr4:
    class: Symfony\Component\Routing\Loader\Psr4DirectoryLoader
    arguments: [ "@file_locator" ]
    tags:
      - { name: loconox_entity_routing.loader, priority: -10 }

  loconox_entity_routing.route.loader.yml:
    class: Symfony\Component\Routing\Loader\YamlFileLoader
    arguments: [ "@file_locator", "%kernel.environment%" ]
    tags:
      - { name: loconox_entity_routing.loader }

  loconox_entity_routing.route.loader.xml:
    class: Symfony\Component\Routing\Loader\XmlFileLoader
    arguments: [ "@file_locator", "%kernel.environment%" ]
    tags:
      - { name: loconox_entity_routing.loader }

  loconox_entity_routing.route.loader.php:
    class: Symfony\Component\Routing\Loader\PhpFileLoader
    arguments: [ "@file_locator", "%kernel.environment%" ]
    tags:
      - { name: loconox_entity_routing.loader }

  loconox_entity_routing.route.loader.container:
    class: Symfony\Component\Routing\Loader\ContainerLoader
    arguments: [ !tagged_locator routing.route_loader, "%kernel.environment%" ]
    tags:
      - { name: loconox_entity_routing.loader }

  loconox_entity_routing.route.loader.glob:
    class: Symfony\Component\Routing\Loader\GlobFileLoader
    arguments: [ "@file_locator", "%kernel.environment%" ]
    tags:
      - { name: loconox_entity_routing.loader }
