services:
    Loconox\EntityRoutingBundle\Slug\SlugServiceManager:
        class: Loconox\EntityRoutingBundle\Slug\SlugServiceManager
        tags:
            - { name: loconox_entity_routing.slug.service.manager }
